services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /opt/app
    ports:
      - "8080:8080"
    volumes:
      - ./offboarding_app/scripts:/opt/app/offboarding_app/scripts:ro
      - ./logs:/var/log
